# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: objective-c
install:
 - gem install xcpretty

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Sailor.xcworkspace -scheme Sailor-Example -sdk iphonesimulator11.3 -destination  "OS=11.3,name=iPhone 8" ONLY_ACTIVE_ARCH=YES SWIFT_VERSION=4.1 | xcpretty
